config/routes.rb
include UrbanFruitProject

Urbanfruitproject::Application.routes.draw do
  
  wiki_root '/wiki'

  match "/404" => 'errors#not_found'
  match "/500" => 'errors#internal_server_error'
  

  get "log_in" => "authorizations#index", :as => "log_in"
  get "sign_up" => "authorizations#index", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  match "/auth/:provider/callback" => "authorizations#create"
  
  get "browse/type(/*hierarchy)" => 'browse#tag'
  get "browse/location(/*hierarchy)" => 'browse#location'
  
  resources :users
  match "/profile" => 'users#profile'
    
  resources :authorizations
  resources :sessions
  resources :images
  resources :tags
  resources :fruit_caches, :path => 'caches' do
    resources :log_entries, :path => 'logs'
  end
  

  match 'search(/:q)' => 'search#index', :as => 'search'
  root :to => 'home#index'
  
  mount UrbanFruitProject::API => "/"
  
  

end

app/controllers/fruit_caches_controller.rb
class FruitCachesController < ApplicationController
  require 'geonames'
  # GET /fruit_caches
  # GET /fruit_caches.xml
  def index
    @fruit_caches = FruitCache.includes( [:tags,:primary_tag]).all
    @google_maps_json = @fruit_caches.to_gmaps4rails do |cache,marker|
      marker.infowindow cache.gmaps4rails_infowindow #render_to_string( :partial => "fruit_caches/map_info", :locals  => { :cache => cache } )
      marker.title cache.name
      marker.sidebar cache.name
      marker.json( { :id => cache.id })
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fruit_caches }
    end
  end

  # GET /fruit_caches/1
  # GET /fruit_caches/1.xml
  def show
    @fruit_cache = FruitCache.find(params[:id])
    @json = @fruit_cache.to_gmaps4rails do |cache, marker|
      "\"id\":#{cache.id}" 
    end
     
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fruit_cache }
    end
  end

  # GET /fruit_caches/new
  # GET /fruit_caches/new.xml
  def new
    @fruit_cache = FruitCache.new
    @fruit_cache.images.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fruit_cache }
    end
  end

  # GET /fruit_caches/1/edit
  def edit  
    @fruit_cache = FruitCache.find(params[:id])
    authorize! :edit, @fruit_cache
  end

  # POST /fruit_caches
  # POST /fruit_caches.xml
  def create    
    authorize! :create, FruitCache
    # Process the comma separated tags
    params[:fruit_cache][:primary_tag_id] = Tag.process_tag_id params[:fruit_cache][:primary_tag_id]
    if params[:fruit_cache][:tags]
      params[:fruit_cache][:tag_ids] = Tag.process_tag_ids params[:fruit_cache][:tags]
      params[:fruit_cache].delete( :tags ) 
    end
    
    @fruit_cache = FruitCache.new(params[:fruit_cache])
    @fruit_cache.user = current_user
  
    
    respond_to do |format|
      if @fruit_cache.save
        
        message = ":user just created a new cache! #{fruit_cache_url( @fruit_cache )}" 
        Tweeter::TimeLine.tweet( message, { :user => current_user.name } ) rescue nil
        
        format.html { redirect_to(@fruit_cache, :notice => 'Fruit cache was successfully created.') }
        format.xml  { render :xml => @fruit_cache, :status => :created, :location => @fruit_cache }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fruit_cache.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fruit_caches/1
  # PUT /fruit_caches/1.xml
  def update
    @fruit_cache = FruitCache.find(params[:id])
    authorize! :update, @fruit_cache
    
    # process the primary tag
    params[:fruit_cache][:primary_tag_id] = Tag.process_tag_id params[:fruit_cache][:primary_tag_id]
    #params[:fruit_cache].delete( :primary_tag )
    
    # Process the comma separated tags
    if params[:fruit_cache][:tags]
      params[:fruit_cache][:tag_ids] = Tag.process_tag_ids( params[:fruit_cache][:tags] )
      params[:fruit_cache].delete( :tags )
    end
    
    respond_to do |format|
      if @fruit_cache.update_attributes(params[:fruit_cache])
        format.html { redirect_to(@fruit_cache, :notice => 'Fruit cache was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fruit_cache.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fruit_caches/1
  # DELETE /fruit_caches/1.xml
  def destroy
    @fruit_cache = FruitCache.find(params[:id])
    authorize! :delete, @fruit_cache
    
    @fruit_cache.destroy

    respond_to do |format|
      format.html { redirect_to(fruit_caches_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/fruit_caches_helper.rb
module FruitCachesHelper
end

app/views/fruit_caches/_form.html.haml
.row
  .span12
    = bootstrap_form_for @fruit_cache, :html => {:multipart => true, :class=>"well form-horizontal"}  do |f|
      - if @fruit_cache.errors.any?
        .alert.alert-block.alert-error
          %a.close{ :'data-dismiss'=>"alert"} 
            ×
          %h4.alert-heading 
            Warning!            
            = pluralize(@fruit_cache.errors.count, "error") + " need to be fixed before we can continue"
          %ul
            - @fruit_cache.errors.full_messages.each do |msg|
              %li
                = msg
      %fieldset

        = f.text_field :primary_tag_id, :label => { text: "Name" } do
          %p.helptext The primary category, usually a name like 'Pear' or 'Morel Mushroom'"
        = f.text_area :description, :class => "input-xlarge", rows: 5
        = f.text_field :tags, :class => "input-xlarge" do
          %p.helptext Anything you think is important such as: 'Poisonous', 'Edible', 'Overpicked'
        
        = f.text_field :latitude, :class => "input-xlarge" do
          %p.helptext Drag the marker on the map below to set automatically
        = f.text_field :longitude, :class => "input-xlarge" do
          %p.helptext Drag the marker on the map below to set automatically
           
        .actions
          = f.submit :class => "btn btn-primary"
        %br
          
      - # Default to the cache lat/long, if none assume it's a new cache and
      - # default to the users ip geolocation
      - latitude = @fruit_cache.latitude || lat_long[:latitude] || request.location.latitude || 0.0
      - longitude = @fruit_cache.longitude || lat_long[:longitude] || request.location.longitude || 0.0
      - zoom = (latitude == 0.0 && longitude == 0.0) ? 4 : 16
      - @markers = "[{\"lng\": \"#{longitude}\", \"lat\": \"#{latitude}\" }]" 

      = gmaps({"map_options" => { "zoom" => zoom, "auto_adjust" => true, "auto_zoom" => false },"markers" => { "data" => @markers, "options" => { "draggable" => true } }})
      
      - content_for :scripts do
        :javascript
          Gmaps.map.callback = function() {
            for (var i = 0; i <  this.markers.length; ++i) {
              google.maps.event.addListener(
                Gmaps.map.markers[i].serviceObject, 
                'dragend', 
                function() { 
                  HandleDragend(this.getPosition()) 
                }
              );
            }
          }
          HandleDragend = function(pos) {
            $( '#fruit_cache_latitude' ).val( pos.lat() );
            $( '#fruit_cache_longitude' ).val( pos.lng() );
          }
          $(document).ready(function () {
              $("#fruit_cache_tags").tokenInput("/api/tags/autocomplete",
                { 
                  theme: "facebook",
                  allowCustomEntry: true,
                  prePopulate: #{'[' + @fruit_cache.tags.map { |tag| "{ id: #{tag.id}, name: \"#{escape_javascript tag.tag}\" }"}.join( ', ' ) + ']'}
                }
              );
              
              $("#fruit_cache_primary_tag_id").tokenInput("/api/tags/autocomplete",
                { 
                  theme: "facebook",
                  tokenLimit: 1,
                  allowCustomEntry: true,
                  prePopulate: #{ (@fruit_cache.primary_tag) ? "[ { id: #{@fruit_cache.primary_tag.id}, name: \"#{escape_javascript @fruit_cache.primary_tag.tag}\" } ]" : "[]" },
                  onAdd: function( item ) {
                    $('#fruit_cache_primary_tag_id').prev().addClass( 'list-full' )
                  },
                  onDelete: function( item ) {
                    $('#fruit_cache_primary_tag_id').prev().removeClass( 'list-full' )
                  },
                  onReady: function( item ) {
                    if( $('#fruit_cache_primary_tag_id').prev().children().size()/2 >= 1 ) {
                      $('#fruit_cache_primary_tag_id').prev().addClass( 'list-full' )
                    }
                  }
                }
              );
          });

app/views/fruit_caches/_map_info.html.haml
%b
  = link_to cache.primary_tag.tag, cache
.description
  = cache.description

app/views/fruit_caches/_show.html.erb
<%= javascript_include_tag "uploadify/swfobject.js", "uploadify/jquery.uploadify.v2.1.4.min.js" %>
<script type="text/javascript" charset="utf-8">
<%- session_key = Rails.application.config.session_options[:key] -%> 
$(document).ready(function() {
	
	$('#image_photo').click(function(event){ 
		event.preventDefault();
	}); 
	
	$('#image_photo').uploadify({
  	uploader : '/javascripts/uploadify/uploadify.swf',
		cancelImg : '/javascripts/uploadify/cancel.png',
		multi : true,
		auto : true,
  	script : '/images',
		onComplete : function(event, queueID, fileObj, response, data) { 
			  var dat = eval('(' + response + ')');
			  $.getScript(dat.image);
			},
  	  scriptData : {
	      '_http_accept': 'application/javascript',
				'format' : 'json',
	      '_method': 'post',
	      '<%= session_key %>' : encodeURIComponent('<%= u cookies[session_key] %>'),
	      'authenticity_token': encodeURIComponent('<%= u form_authenticity_token %>'),
				'fruit_cache_id' : '<%= @fruit_cache.id %>'
	    }
	});
	
	$('#image_submit').click(function(event){ 
			event.preventDefault(); 
			$('#image_photo').uploadifyUpload(); 
		});
		
}); 
</script>

app/views/fruit_caches/_snippet.html.haml
.row
  .span6.cache
    .controls.pull-right
      %ul.unstyled
        - if can? :edit, fruit_cache
          %li
            .i.icon-cog
            = link_to 'Edit', edit_fruit_cache_path(fruit_cache)
        - if can? :delete, fruit_cache
          %li
            .i.icon-remove
            = link_to 'Destroy', fruit_cache, :'data-method'=>"delete",:'data-confirm' => 'Are you sure?', :method => :delete
    .thumbnail.pull-left
      - if fruit_cache.images.size > 0
        %img{ :src => fruit_cache.images[0].photo.url(:micro_crop), :class => "span1" }
      - else
        %img{ :src => asset_path( "missing_micro.png"), :class => "span1" }
    %div
      = link_to fruit_cache.primary_tag.tag, fruit_cache
    %div
      = fruit_cache.location

app/views/fruit_caches/_uploadify.html.erb
<%= javascript_include_tag "uploadify/swfobject.js", "uploadify/jquery.uploadify.v2.1.4.min.js" %>
<script type="text/javascript" charset="utf-8">
<%- session_key = Rails.application.config.session_options[:key] -%> 
$(document).ready(function() {
	
	$('#image_photo').click(function(event){ 
		event.preventDefault();
	}); 
	
	$('#image_photo').uploadify({
	  buttonText : "Upload photos...",
  	uploader : "<%= asset_path 'uploadify.swf' %>",
		cancelImg : "<%= asset_path 'cancel.png' %>",
		multi : true,
		auto : true,
  	script : '/images',
  	onError : function( event, id, fileObj, errorObj ) {
	    alert( errorObj.info )
  	},
		onComplete : function(event, queueID, fileObj, response, data) { 
			  var dat = eval('(' + response + ')');
			  $.getScript(dat.image);
			},
  	  scriptData : {
	      '_http_accept': 'application/javascript',
				'format' : 'json',
	      '_method': 'post',
	      '<%= session_key %>' : encodeURIComponent('<%= u cookies[session_key] %>'),
	      'authenticity_token': encodeURIComponent('<%= u form_authenticity_token %>'),
				'fruit_cache_id' : '<%= @fruit_cache.id %>'
	    }
	});
	
	$('#image_submit').hide();
	$('#image_submit').click(function(event){ 
			event.preventDefault(); 
			$('#image_photo').uploadifyUpload(); 
		});
		
}); 
</script>

app/views/fruit_caches/edit.html.haml
%h1
  = "Editing #{(@fruit_cache.primary_tag) ? @fruit_cache.primary_tag.tag : "cache"}"

= render 'form'

= link_to 'Show', @fruit_cache 
|
= link_to 'Back', fruit_caches_path 

app/views/fruit_caches/index.html.haml
- title "Caches near you"

.row
  .span12
    = gmaps( "markers" => { "data" => @google_maps_json, "options" => { "do_clustering"=>true, "clusterer_maxZoom"=>13 } }, "map_options" => { :container_class => "map_container", :class => "height500", :auto_adjust => true } )

app/views/fruit_caches/new.html.haml
- if can? :create, FruitCache 
  - title "Record Your Find"
  = render 'form'
- else
  .hero-unit
    %h1 User account needed :'( 
    %p We are terribly sorry but we need you to log in or create an account first before you can record your new found stash of goodies.  We promise it's easy!
    %p
      %a{ :class => "btn btn-primary btn-large", :href => log_in_path  } Log In
      %a{ :class => "btn btn-large", :href => sign_up_path  } Create An Account

app/views/fruit_caches/show.html.haml
- title @fruit_cache.primary_tag.tag

- if can? :edit, @fruit_cache
  .row
    .span6
      .i.icon-cog
      = link_to 'Edit', edit_fruit_cache_path(@fruit_cache)
    
.row
  .span6
    %p
      - @fruit_cache.tags.each do |tag|
        = render :partial => 'tags/tag', :locals => { :tag => tag }
    
    %p
      = @fruit_cache.description
    
    - attribution = []  
    - @fruit_cache.tags.each do |tag|
      - tag.meta.reduce( attribution ) { |attribution, (k,v)| k == attribution << v if 'Attribution' }
    - if attribution.count > 0
      Provided by:
      %ul
        - attribution.each do |link|
          %li= raw(link)
        
    %h3#photos_count
      -if @fruit_cache.images.size > 0
        = pluralize(@fruit_cache.images.size, "Photo")
      -else
        = "No photos :'("

    #slideshowModal.modal.modal-fullwidth.fade{ :style=>"display: none"}
      .modal-header
        %a.close{:'data-dismiss'=>"modal"} ×
        %h3 Slideshow
      .modal-body
        - if @fruit_cache.images && @fruit_cache.images.count > 0
          #myCarousel.carousel
            .carousel-inner
              - @fruit_cache.images[0..0].each do |image|
                .item.active
                  = image_tag image.photo.url(:fullwidth_crop)
                  - if image.caption
                    .carousel-caption
                      = image.caption
              - if @fruit_cache.images && @fruit_cache.images.count > 1
                - @fruit_cache.images[1..-1].each do |image|
                  .item
                    = image_tag image.photo.url(:fullwidth_crop)
                    - if image.caption
                      .carousel-caption
                        = image.caption
            - if @fruit_cache.images && @fruit_cache.images.count > 1 
              %a.carousel-control.left{ :href=>'#myCarousel', :'data-slide'=>"prev"} &lsaquo;
              %a.carousel-control.right{ :href=>'#myCarousel', :'data-slide'=>"next"} &rsaquo;

        

    %ul.thumbnails#images
      - @fruit_cache.images.each do |image|
        %li
          %a{'data-toggle'=>"modal", :href=>"#slideshowModal"}
            = render :partial => "images/smallthumbnail", :locals => { :image => image }

    - if can? :create, Image
      = render :partial => "uploadify"
      = form_for Image.new(:fruit_cache_id => @fruit_cache.id), :html => {:multipart => true} do |f|
        = f.hidden_field :fruit_cache_id, "value" => @fruit_cache.id
        %p
          = f.file_field :photo
        %p
          = f.submit "Upload photos...", :id => "image_submit"
    - else
      Log in to upload photos

    %h3 Logs
    - @fruit_cache.log_entries.each do |log|
      .row
        .span6
          = render :partial => 'log_entries/log_entry', :locals => { :log => log }

    - if can? :create, LogEntry
      = link_to 'Add log entry', new_fruit_cache_log_entry_path( @fruit_cache )
    - else
      Log in to add your logs
      
  .span6
    = gmaps( :map_options => { :container_class => "map_container", :class => "height300", :auto_adjust => true, :auto_zoom => false, :zoom => 16 },:markers => { "data" => @json} )
    
    %h3
      Nearby Caches
    - @fruit_cache.nearbys( 20, { :limit => 5 }).each do |cache|
      = render :partial => "fruit_caches/snippet", :locals => { :fruit_cache => cache }