config/routes.rb
include UrbanFruitProject

Urbanfruitproject::Application.routes.draw do
  
  wiki_root '/wiki'

  match "/404" => 'errors#not_found'
  match "/500" => 'errors#internal_server_error'
  

  get "log_in" => "authorizations#index", :as => "log_in"
  get "sign_up" => "authorizations#index", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  match "/auth/:provider/callback" => "authorizations#create"
  
  get "browse/type(/*hierarchy)" => 'browse#tag'
  get "browse/location(/*hierarchy)" => 'browse#location'
  
  resources :users
  match "/profile" => 'users#profile'
    
  resources :authorizations
  resources :sessions
  resources :images
  resources :tags
  resources :fruit_caches, :path => 'caches' do
    resources :log_entries, :path => 'logs'
  end
  

  match 'search(/:q)' => 'search#index', :as => 'search'
  root :to => 'home#index'
  
  mount UrbanFruitProject::API => "/"
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations, :dependent => :destroy
  has_many :fruit_caches, :class_name => "fruit_cache", :foreign_key => "user_id"
  
  validates_presence_of :email, :message => "can't be blank"
  validates_presence_of :name, :message => "can't be blank"

  def self.create_from_hash!(hash)
    create(:name => hash['info']['name'])
  end
  
  def build_authorization( omniauth )
    self.email = omniauth['info']['email'] if email.blank?
    authorizations.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :json
  
  
  def index
    @users = User.all
    respond_with @users  
  end

  def show
    @user = User.find(params[:id])
    respond_with @user
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def new
    if !session.has_key?(:omniauth) 
      flash[:error] = "NO authorizations associated with new user"
      redirect_to new_user_path
    end
    @user = User.new
    @user.valid?
  end
  
  def create
    @user = User.new(params[:user])
    @user.token = Digest::SHA1.hexdigest([Time.now, rand].join)
    
    #clear omniauth data if it is in the session
    if session.has_key?(:omniauth) 
      @user.build_authorization(session[:omniauth])
      @user.valid?
    end
    
    if @user.save
      session[:omniauth] = nil
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
  
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id]) || current_user
    @user.destroy
    flash[:notice] = "User destroyed"
    redirect_to root_url
  end
  
  def profile
    
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= bootstrap_form_for @user, :html => {:multipart => true, :class=>"well form-horizontal"}  do |f|
  - if @user.errors.any?
    .alert.alert-block.alert-error
      %a.close{ :'data-dismiss'=>"alert"} 
        ×
      %h4.alert-heading 
        Warning!
        = pluralize(@user.errors.count, "error") + " need to be fixed before we can continue"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li
            = msg

  = f.text_field :name
  = f.text_field :email
  
  = f.submit "Submit", :disable_with => 'Submiting...'

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>name</th>
    <th>email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Log entry', new_user_path( @user ) %>

app/views/users/new.html.haml
%h1 
  Sign Up

= render 'form'

app/views/users/profile.html.haml
- title( current_user.name )
.row 
  .span6
    %h3 Users tasks
    %ul
      %li
        %a{ :href => edit_user_path( current_user ) }
          Edit your profile
      %li
        %a{ :href => authorizations_path }
          Edit your authorizations
      %li
        %a{ :href=>"urbanfruitproject://authorize?user_id=#{current_user.id}&token=#{current_user.token}" }
          Authorize your mobile app (beta only)
  .span6
    %h3 Your caches
    - caches = FruitCache.where( :user_id => current_user )
    - if caches && !caches.nil?
      %ul
        - caches.each do |cache|
          %li
            %a{ :href => fruit_cache_path(cache.id)}
              = "#{cache.primary_tag.tag}"
            =  " - #{cache.location}"
    - else
      %p No caches :'(

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>
<p>
    <b>Email:</b>
    <%= @user.email %>
</p>


<%= link_to 'Add user', new_user_path( @user )%>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>