config/routes.rb
include UrbanFruitProject

Urbanfruitproject::Application.routes.draw do
  
  wiki_root '/wiki'

  match "/404" => 'errors#not_found'
  match "/500" => 'errors#internal_server_error'
  

  get "log_in" => "authorizations#index", :as => "log_in"
  get "sign_up" => "authorizations#index", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  match "/auth/:provider/callback" => "authorizations#create"
  
  get "browse/type(/*hierarchy)" => 'browse#tag'
  get "browse/location(/*hierarchy)" => 'browse#location'
  
  resources :users
  match "/profile" => 'users#profile'
    
  resources :authorizations
  resources :sessions
  resources :images
  resources :tags
  resources :fruit_caches, :path => 'caches' do
    resources :log_entries, :path => 'logs'
  end
  

  match 'search(/:q)' => 'search#index', :as => 'search'
  root :to => 'home#index'
  
  mount UrbanFruitProject::API => "/"
  
  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  include Tanker
  acts_as_tree
  
  serialize :meta, Hash
  #attr_accessor :meta
  #before_save :handle_meta_edit, :if => lambda {|t| t.meta_edit.present? }
  
  has_and_belongs_to_many :fruit_caches
  
  after_save :update_tank_indexes
  after_destroy :delete_tank_indexes
  
  tankit Rails.configuration.indextank_index do
    indexes :tag
  end
  
  # This takes a comma separated string of Id's and
  # new values (strings) and converts to an array of
  # id's.  New values are first saved.
  #
  # Example Input: "1,5,43,'new-tag',12"
  def self.process_tag_ids( tagIdString )
    debugger
    parts = tagIdString.split( "," ).map(&:strip).reject(&:empty?)
    tagIds = []
    parts.each do |part|
      tag_id = Tag.process_tag_id part
      tagIds << tag_id
    end
    
    tagIds
  end
  
  def self.process_tag_id( tag_string )
    return if tag_string.blank?
    begin  
      id = Integer tag_string
      return id
    rescue
      tag = Tag.new( :tag => tag_string.tr( "'", "" ) )
      tag.save
      return tag.id
    end
  end
  
  # protected
  # def handle_meta_edit
  #   # You may want to perform eval in your validations instead of in a 
  #   # before_save callback, so that you can show errors on your form.
  #   debugger
  #   begin
  #     self.meta = eval(meta_edit)
  #   rescue SyntaxError => e
  #     self.meta = meta_edit
  #   end
  # end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource :except => [:create]
  respond_to :html
  
  def index
    @tags = Tag.all 
    respond_with @tags
  end

  def show
    respond_with @tag
  end
  
  def new
    debugger
    @tag = Tag.new
    
    respond_with @tag
  end
  
  def create  
    authorize! :create, Tag

    params[:tag][:parent_id] = Tag.process_tag_id( params[:tag][:parent] )
    params[:tag].delete( :parent )
    
    @tag = Tag.new(params[:tag])  
    
    respond_to do |format|
      if @tag.save
        format.html { redirect_to(@tag, :notice => 'Fruit cache was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def edit
    #@tag.meta_edit = @tag.read_attribute(:meta).inspect
  end
  
  def update
    params[:tag][:parent_id] = Tag.process_tag_id( params[:tag][:parent] )
    params[:tag].delete( :parent )

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
    
  end

end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/tags/_form.html.haml
= bootstrap_form_for @tag, :html => {:multipart => true, :class=>"well form-horizontal"}  do |f|
  = f.text_field :tag
  = f.text_field :parent
  
  - Rails.logger.debug @tag.inspect
  - Rails.logger.debug @tag.meta
  - @tag.meta.each do |key, value|
    = render :partial => "generic_property_form", :locals => { :key => key, :value => value }
  .control-group
    .controls
      = link_to_function( "Add", "add_fields( this, \"#{escape_javascript(render :partial=>"generic_property_form", :locals=>{ :key=>"newkey", :value => "value"})}\")" )
        
  .actions
    = f.submit :class => "btn btn-primary"
  
- content_for :scripts do
  :javascript
    $(document).ready(function () {
        $("#tag_parent").tokenInput("/api/tags/autocomplete",
          { 
            theme: "facebook",
            tokenLimit: 1,
            allowCustomEntry: true,
            prePopulate: #{ (@tag.parent) ? "[ { id: #{@tag.parent.id}, name: \"#{escape_javascript @tag.parent.tag}\" } ]" : "[]" },
            onAdd: function( item ) {
              $('#tag_parent').prev().addClass( 'list-full' )
            },
            onDelete: function( item ) {
              $('#tag_parent').prev().removeClass( 'list-full' )
            },
            onReady: function( item ) {
              if( $('#tag_parent').prev().children().size()/2 >= 1 ) {
                $('#tag_parent').prev().addClass( 'list-full' )
              }
            }
          }
        );
    });

app/views/tags/_generic_property_form.html.haml
.control-group
  = label_tag key, nil, :class => 'control-label edittable-label' 
  =# text_field_tag "label", key, :style=>"width: 135px; float: left; padding-top: 5px;"
  .controls
    = text_field_tag "tag[meta][#{key}]", value
    = link_to_function "Remove", "remove_field(this)"

app/views/tags/_tag.html.haml
.tag
  %a{ :href => tag_path( tag ) }
    %span.parent= (tag.parent) ? "#{tag.parent.tag} >" : ""
    %span.name= "#{tag.tag}"

app/views/tags/edit.html.haml
- title( "Edit tag")
= render 'form' 

app/views/tags/index.html.haml
%ul
  - @tags.each do |tag|
    %li= "#{tag.tag}"

app/views/tags/new.html.haml
- if can? :create, Tag 
  - title "New Tag"
  = render 'form'

app/views/tags/show.html.haml
- title( @tag.tag )

.row
  .span6
    .tag
      = @tag.tag
    =link_to( "Edit", edit_tag_path( @tag ) )
    .parent
      - if @tag.parent
        .parent
          = "#{@tag.parent.tag} #{(@tag.parent.id)}"
      - else
        No parent
    .children
      - if @tag.children.count > 0
        = @tag.children
      - else
        No Children
    .meta
      %dl
        - @tag.meta.each do |key,value|
          %dt= key
          %dd= value