config/routes.rb
include UrbanFruitProject

Urbanfruitproject::Application.routes.draw do
  
  wiki_root '/wiki'

  match "/404" => 'errors#not_found'
  match "/500" => 'errors#internal_server_error'
  

  get "log_in" => "authorizations#index", :as => "log_in"
  get "sign_up" => "authorizations#index", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  match "/auth/:provider/callback" => "authorizations#create"
  
  get "browse/type(/*hierarchy)" => 'browse#tag'
  get "browse/location(/*hierarchy)" => 'browse#location'
  
  resources :users
  match "/profile" => 'users#profile'
    
  resources :authorizations
  resources :sessions
  resources :images
  resources :tags
  resources :fruit_caches, :path => 'caches' do
    resources :log_entries, :path => 'logs'
  end
  

  match 'search(/:q)' => 'search#index', :as => 'search'
  root :to => 'home#index'
  
  mount UrbanFruitProject::API => "/"
  
  

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  belongs_to :fruit_cache
  
  has_attached_file :photo, 
    :styles => { 
      :micro_crop => "40x40#",
      :thumbnail_crop => "60x60#",
      :halfwidth => "460",
      :halfwidth_crop => "460x345#",
      :fullwidth => "940",
      :fullwidth_crop => "940x550#"
    },
    :storage => :s3,
    :bucket => ENV['PAPERCLIP_S3_BUCKET'],
    :path => 'paperclip_assets/:attachment/:id/:style/:filename',
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET']
    }
  
  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  load_and_authorize_resource
  
  # GET /uploads
  # GET /uploads.xml
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.xml
  def show
    #debugger
    @image = Image.find(params[:id])
  end

  # GET /uploads/new
  # GET /uploads/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /uploads/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.xml
  def create

    newparams = coerce(params)
    @image = Image.new(newparams[:image])
    @image.user = current_user
    if @image.save
      flash[:notice] = "Successfully created Image."

      Tweeter::TimeLine.tweet "A new image was added to #{@image.fruit_cache.name}: #{fruit_cache_url( @image.fruit_cache )}"
      
      respond_to do |format|
        format.html {redirect_to @image.fruit_cache}
        format.json {render :json => { :result => 'success', :image => image_path(@image) } }
      end
    else
      render :action => 'new'
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.xml
  def update
    @image = Image.find(params[:id])
    
    respond_to do |format|
      if @Image.update_attributes(params[:image])
        format.html { redirect_to(@image, :notice => 'Upload was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @Image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.xml
  def destroy
    @image = Image.find(params[:id])

    @image.destroy
      
    respond_to do |format|
      format.html { redirect_to(params[:redirect_to] || images_url) }
      format.xml  { head :ok }
    end
  end
  
  private 
  def coerce(params)
    if params[:image].nil? 
      h = Hash.new 
      h[:image] = Hash.new 
      h[:image][:fruit_cache_id] = params[:fruit_cache_id] 
      h[:image][:photo] = params[:Filedata] 
      h[:image][:photo].content_type = MIME::Types.type_for(h[:image][:photo].original_filename).to_s
      h
    else 
      params
    end 
  end


end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.haml
= form_for(@image) do |f|
  - if @image.errors.any?
    #error_explanation
      %h2
        = pluralize(@image.errors.count, "error") + "prohibited this upload from being saved:"
      %ul
      - @image.errors.full_messages.each do |msg|
        %li
          = msg

  .field
    = f.file_field :photo
    
  .field
    = f.label :fruit_cache_id
    %br
    = f.text_field :fruit_cache_id
    
  .field
    = f.label :caption
    = f.text_field :caption
  
  .actions
    = f.submit

app/views/images/_image.html.erb
<div class="upload"> 
	<%= image_tag image.photo.url(:small) %>
	<%= link_to 'Remove image', image_path(image, :redirect_to => fruit_cache_path(image.fruit_cache)), :method => :delete %>
</div>

app/views/images/_smallthumbnail.html.haml
%div.thumbnail
  = image_tag image.photo.url(:thumbnail_crop)
  %p
    = image.caption
  - if can? :delete, image 
    = link_to image_path(image, :redirect_to => fruit_cache_path(image.fruit_cache)), :'data-method'=>"delete",:'data-confirm' => 'Are you sure?', :method => :delete do
      %i.icon-remove.pull-right
    %div{ :style => "clear: right;" }

app/views/images/new.html.haml
= render 'form'
= link_to 'Back', images_path

app/views/images/show.js.erb
$('ul#images').append("<li><%= escape_javascript(render(:partial => "images/smallthumbnail", :locals => {:image => @image})) %></li>");